export const movies =[ { 
title:"Toy Story ", 
genre:"Animação ", 
ageRating: 10, 
synopsis:"A historia de um grupo de brinquedo que ganham vida quando não há humanos por "
trailer: https://www.bing.com/ck/a?!&&p=4af530394e010c4dfc0b217c1b48fb63b33ef0e1c79fc22a5411784a522fa924JmltdHM9MTczMDkzNzYwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&psq=trailer+toy+story&u=a1aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1DeHdUTGt0b3ZUVQ&ntb=1”"" 
}, 
{ 
title: "moana", 
genre:"Aventura", 
ageRating: 10, 
synopsis:":MOANA é uma jovem polinésia corajosa e determinada,filha do chefe de uma tribo que proibe a navegação pelo oceano", 
trailer:https://www.bing.com/ck/a?!&&p=e63c237099b8e294ab508e74b4f507627c42887901a5e82177b54e6e84e744f1JmltdHM9MTczMDkzNzYwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&psq=trailer+de+moaana+1&u=a1aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj04akFaRjZ1azdLVQ&ntb=1 "" 
}, 
{ 
title: "meu malvado favorito"",", 
genre:"Comédia", 
ageRating: 10, 
synopsis: "Gru é um supervilão que adora todas as coisas diabólicas e planeja roubar a lua!", 
trailer:https://www.bing.com/ck/a?!&&p=b214d773922537fa94daae55219e6f73fd86902498f2a2330e34c71fa785c265JmltdHM9MTczMDkzNzYwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&psq=trailer+do+meu+malvado+favorito&u=a1aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1zZVNJSmY1bWhQRQ&ntb=1 "" 
}, 
{ 
title: "A Bruxa de Blair", 
genre: "Terror", 
ageRating: 13, 
synopsis: "A historia se desenrola como um achado:filmagens amadoras de um grupo de estudantes universitários que desaparecem mistoriosamente ao investigar a lenda da bruxa de Blair em uma floresta de Maryland.", 
trailer:https://www.youtube.com/watch?v=2wGUeGYdTAc&pp=ygUadHJhaWxlciBkYSBicnV4YSBkZSBibGFpciA%3D "" 
}, 
{ 
title:"Jumanji:o proximo nive", 
genre: Aventura,Comédia,Ação"", 
ageRating: 13, 
synopsis:"a sequencia de “Bem-vindo á Selva”, onde os amigos retornam  ao mundo de Jumanji para resgatar um dos seus e descobrem que o jogo mudou  e traz novos desafios", 
trailerhttps://www.youtube.com/watch?v=65FjlYSLalk&pp=ygUhdHJhaWxlciAganVtYW5qaTogbyBwcm94aW1vIG5pdmVs: "" 
}, 
{ 
title:"duna ", 
genre:"Aventura,", 
ageRating: 16, 
synopsis:."Duna é uma épica jornada de u m jovem que se descobre e se transforma em um lider,equanto luta por justiça e SOBREVIVÊNCIA em um universo hostil e cheio de intrigas  políticas", 
trailer:https://www.youtube.com/watch?v=dnBpZuSUISQ&pp=ygUNdHJhaWxlciAgZHVuYQ%3D%3D "" 
}, 
{ 
title:Spider-verse "",
genre: "ação", 
ageRating: 16, synopsis:"picado por u ma Acompanhamos a jornada  de miles Morales,um adolescente  negro do Brookyn que se torna o Homem-Aranha após ser aranha radioativa", 
trailer:https://www.youtube.com/watch?v=g4Hbz2jLxvQ&pp=ygUVdHJhaWxlciAgc3BpZGVyLXZlcnNl"" 
}, 
{ 
title:"O Poderoso Chefão", 
genre: "ação", 
ageRating: 18, synopsis:."A trana se desenrola em torno do casamento  da filha de vito ,Connie.Durante a festa,diversos membros da familia e aliados buscam seus favoritos  No entanto,a tranquilidade é abalada por u ma tentativa de assassinato contra Don Vito,que o deixa incapacitado", 
trailer:https://www.bing.com/ck/a?!&&p=9571be7a3bb4664f72b8db9e4069ce5b96fc33d7702d119c00571b46c1c6edadJmltdHM9MTczMDkzNzYwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&psq=o+poderoso+chef%c3%a3o+trailer&u=a1aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj0wdjZNTzBFQjdVWQ&ntb=1 "" 
}, 
{ 
title:https://www.bing.com/ck/a?!&&p=9571be7a3bb4664f72b8db9e4069ce5b96fc33d7702d119c00571b46c1c6edadJmltdHM9MTczMDkzNzYwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&psq=o+poderoso+chef%c3%a3o+trailer&u=a1aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj0wdjZNTzBFQjdVWQ&ntb=1 "", 
genre: "", 
ageRating: 16, synopsis: "", 
trailer: "" 
}, 
{ 
title: "", 
genre: "", 
ageRating: 13, synopsis: "", 
trailer: "" 
}, 
{ 
title: "Amor e Monstros", 
genre: "Ficção científica", 
ageRating: 16, synopsis: "amor e Monstros é um filme que se passa em um mundo pós-apocalíptico,onde criatura gigantes dominam a Terra e a humanidades se refugia em colônias subterrâneas", 
trailer: "https://www.bing.com/ck/a?!&&p=710dc0ea6607664b174e62ba2010a31c4014fe67c2be337361cf81063c736bfaJmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&u=a1L3ZpZGVvcy9zZWFyY2g_cT10cmFpbGVyK2Ftb3IrZSttb25zdHJvcyZxcHZ0PXRyYWlsZXIrYW1vcitlK21vbnN0cm9zJkZPUk09VkRSRQ&ntb=1" 
}, 
{ 
title: "Parasita", 
genre: "Drama", 
ageRating: 18, synopsis: "Parasita é um filme sul-coreano que conquistou o mundo com sua narrativa intrigante e crítica social afiada. A trama gira em torno de duas famílias: os Kims, pobres e desempregados, vivendo em um porão apertado e úmido; e os Parks, ricos e bem-sucedidos, ocupando uma mansão luxuosa.", 
trailer: "https://www.bing.com/ck/a?!&&p=8349cb59f8e4856ad0bc7a3bb48a77ccfbbd49daae5cc9914a3944d54044475eJmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&u=a1L3ZpZGVvcy9zZWFyY2g_cT10cmFpbGVyK2RvK2ZpbG1lK3BhcmFzaXRhJnFwdnQ9dHJhaWxlcitkbytmaWxtZStwYXJhc2l0YSZGT1JNPVZEUkU&ntb=1" 
}, 
{ 
title: "A chegada", 
genre: "Suspense", 
ageRating: 18, synopsis: "A Chegada é um filme de ficção científica que nos leva a uma jornada intrigante e emocionante sobre a comunicação e a percepção do tempo. Quando naves alienígenas misteriosas pousam em diversas partes do globo, a humanidade se vê à beira de um conflito global.", 
trailer: "https://www.bing.com/ck/a?!&&p=6adf37401942e1caa77fb223d03a5710b2f4779020dc503418663f7141482f5bJmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&u=a1L3ZpZGVvcy9zZWFyY2g_cT10cmFpbGVyK2RvK2ZpbG1lK0ErY2hlZ2FkYSZxcHZ0PXRyYWlsZXIrZG8rZmlsbWUrQStjaGVnYWRhJkZPUk09VkRSRQ&ntb=1" 
},
{ 
title: "Matilda", 
genre: "Comédia", 
ageRating: 13, 
synopsis: "Matilda é um clássico do cinema infantil que conta a história de uma menina brilhante e cheia de imaginação que não tem uma vida fácil em casa. Seus pais são grosseiros e ignoram completamente seu intelecto.", 
trailer: "https://www.bing.com/ck/a?!&&p=62cc2b0fcc1d4cfdca26d724145480d19d617dbb54483d284944a5acf990ea1aJmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&u=a1L3ZpZGVvcy9zZWFyY2g_cT10cmFpbGVyK2RvK2ZpbG1lK21hdGlsZGEmcXB2dD10cmFpbGVyK2RvK2ZpbG1lK21hdGlsZGEmRk9STT1WRFJF&ntb=1" 
}, 
{ 
title: "A culpa é das Estrelas", 
genre: "Drama", 
ageRating: 16, 
synopsis: "A Culpa é das Estrelas é um filme emocionante que aborda o tema da vida, da morte e do amor de forma profunda e comovente. A história gira em torno de Hazel Grace Lancaster, uma adolescente diagnosticada com câncer, que se mantém viva graças a um tratamento experimental.", 
trailer: "https://www.bing.com/ck/a?!&&p=07cc06ff90e3e23d9e7eb913f2f591860d8fa5571fe6ad9b6658dee6b240435eJmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&u=a1L3ZpZGVvcy9zZWFyY2g_cT10cmFpbGVyK2RvK2ZpbG1lK0ErY3VsdGErZGFzK2VzdHJsYXMmcXB2dD10cmFpbGVyK2RvK2ZpbG1lK0ErY3VsdGErZGFzK2VzdHJsYXMmRk9STT1WRFJF&ntb=1" 
}, 
{ 
title: "O labirinto", 
genre: "Suspense", 
ageRating: 13, 
synopsis: "O Labirinto é um clássico do cinema que transporta o público para um mundo fantástico e cheio de aventuras. A história gira em torno de Sarah, uma adolescente que, frustrada por ter que cuidar do seu irmão mais novo, faz um pedido impulsivo: que o Rei dos Duendes leve o bebê para longe.", 
trailer: "https://www.bing.com/ck/a?!&&p=f09d9ebbf1f5f303ee09f4104e0ac02b829071e832f75bae2a883965f9055c7eJmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&psq=o+filme+do+labirinto&u=a1aHR0cHM6Ly93d3cuYWRvcm9jaW5lbWEuY29tL2ZpbG1lcy9maWxtZS0yNzUxMzAv&ntb=1" 
}, 
{ 
title: "A lista de Schindler", 
genre: "Drama histórico", 
ageRating: 18, 
synopsis: "O filme se concentra na figura de Oskar Schindler, um empresário alemão e membro do Partido Nazista que, inicialmente motivado por interesses próprios, acaba salvando a vida de mais de mil judeus durante a Segunda Guerra Mundial.", 
trailer: "https://www.bing.com/ck/a?!&&p=68a75036f9d04c4c77439ce1f0b978c5420458bdfb9ac58456172ba921a50cb3JmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&u=a1L3ZpZGVvcy9zZWFyY2g_cT10cmFpbGVyK2RvK2ZpbG1lK2ErbGlzdGErZGUrc2NoaW5kbGVyJnFwdnQ9dHJhaWxlcitkbytmaWxtZSthK2xpc3RhK2RlK3NjaGluZGxlciZGT1JNPVZEUkU&ntb=1" 
}, 
{ 
title: "Por lugares incríveis", 
genre: "Drama", 
ageRating: 13, 
synopsis: "Por Lugares Incríveis é um filme que aborda temas como depressão, suicídio e saúde mental de forma delicada e tocante. A história acompanha Violet Markey, uma adolescente que luta contra a depressão após a perda de sua irmã em um acidente. Isolada e com pensamentos suicidas, Violet encontra um ponto de virada quando conhece Theodore Finch, um jovem enigmático que também enfrenta suas próprias batalhas internas.", 
trailer: "https://www.bing.com/ck/a?!&&p=7add2d1e243d95925a4e346ee7b10f3449ed1d9b2e3979e9e912d5ca82c6fa01JmltdHM9MTczMTAyNDAwMA&ptn=3&ver=2&hsh=4&fclid=1da75c4d-2c14-6d09-0f3a-48c12def6c66&psq=trailer+do+filme+por+lugares+incriveis&u=a1aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj10ZHdMUkhHUVZHOA&ntb=1" 
} 
];
